In [1]:
import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.text import one_hot
import re

In [2]:
from tqdm import tqdm
tqdm.pandas()

In [ ]:
# twitter_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Bayesian Learning/Project 1/Trial 5/train.csv', encoding = 'ISO-8859-1')
# df = twitter_data.iloc[:6000]
# df.head()

id   Latitude   Longitude  \
0  USER_131347  25.587695  -80.379636   
1  USER_321775  34.046692 -117.524254   
2  USER_139842  42.286785  -85.590620   
3  USER_362638  39.355249  -76.598514   
4  USER_311240  40.648491  -73.962830   

                                               tweet  tweet_count  \
0                       @USER_4beb918b followingg (:           24   
1  @USER_c586797f WHATZ GREAT MANN OF GOD, IF YOU...           33   
2  @USER_03159296 I'd have to go with the snow, i...           38   
3                             @USER_bcfa504a yup lol           20   
4                   Ladies be nice. No rude behavior           20   

                                    tweet_timestamps  
0  ['23:40:22', '11:39:18', '19:50:35', '21:29:39...  
1  ['22:50:47', '01:10:21', '03:13:05', '03:30:42...  
2  ['23:40:01', '23:42:45', '00:02:50', '00:09:07...  
3  ['16:51:44', '17:40:36', '17:48:26', '17:49:08...  
4  ['23:24:15', '23:56:40', '00:03:54', '02:53:08...

In [ ]:
# def remove_user_tweet(tweet):
#     pattern = '[@][a-zA-Z0-9_]*'
#     #matches = re.findall(pattern  ,tweet)
#     match = re.compile( '[@][a-zA-Z0-9_]*')
#     sentence = match.sub('', tweet)
#     return sentence

In [ ]:
#df.loc[:,'tweet w/o user'] = df.loc[:,'tweet'].apply(remove_user_tweet)

<ipython-input-4-8ec2d1654db1>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:,'tweet w/o user'] = df.loc[:,'tweet'].apply(remove_user_tweet)


In [ ]:
# df

id   Latitude   Longitude  \
0     USER_131347  25.587695  -80.379636   
1     USER_321775  34.046692 -117.524254   
2     USER_139842  42.286785  -85.590620   
3     USER_362638  39.355249  -76.598514   
4     USER_311240  40.648491  -73.962830   
...           ...        ...         ...   
5995  USER_306230  40.685128  -73.581845   
5996  USER_247488  41.650608  -70.299491   
5997  USER_325702  39.070599  -77.011907   
5998  USER_235606  33.649463  -84.002263   
5999  USER_298845  35.995759  -78.888912   

                                                  tweet  tweet_count  \
0                          @USER_4beb918b followingg (:           24   
1     @USER_c586797f WHATZ GREAT MANN OF GOD, IF YOU...           33   
2     @USER_03159296 I'd have to go with the snow, i...           38   
3                                @USER_bcfa504a yup lol           20   
4                      Ladies be nice. No rude behavior           20   
...                                                 ...          ...   
5995  #beforeidie i wanna hav a family, somethin lik...           75   
5996  @USER_88b09e4d im not trying to ! i told her i...           23   
5997  RT @USER_8bde831b: Almost lunch thank God just...           41   
5998  aaahhh just read @USER_34876f43 dm...where my ...           43   
5999  If I had a girlfriend, she wud have a girlfrie...           25   

                                       tweet_timestamps  \
0     ['23:40:22', '11:39:18', '19:50:35', '21:29:39...   
1     ['22:50:47', '01:10:21', '03:13:05', '03:30:42...   
2     ['23:40:01', '23:42:45', '00:02:50', '00:09:07...   
3     ['16:51:44', '17:40:36', '17:48:26', '17:49:08...   
4     ['23:24:15', '23:56:40', '00:03:54', '02:53:08...   
...                                                 ...   
5995  ['22:58:19', '23:45:29', '00:16:39', '00:18:38...   
5996  ['14:39:16', '14:55:18', '15:03:54', '15:07:45...   
5997  ['22:45:21', '22:47:06', '22:49:13', '22:54:22...   
5998  ['22:43:27', '22:43:47', '22:50:12', '00:55:55...   
5999  ['02:42:09', '03:56:38', '13:24:48', '14:29:09...   

                                         tweet w/o user  
0                                         followingg (:  
1      WHATZ GREAT MANN OF GOD, IF YOUR NOT FOLLOWIN...  
2      I'd have to go with the snow, it's much cleaner.  
3                                               yup lol  
4                      Ladies be nice. No rude behavior  
...                                                 ...  
5995  #beforeidie i wanna hav a family, somethin lik...  
5996   im not trying to ! i told her id help her its...  
5997  RT : Almost lunch thank God just 5mins left I'...  
5998  aaahhh just read  dm...where my lil bro  at..f...  
5999  If I had a girlfriend, she wud have a girlfrie...  

[6000 rows x 7 columns]

In [ ]:
# import pandas as pd
# import re
# import nltk
# import spacy
# import numpy as np
# from textblob import TextBlob
# import gensim
# nlp = spacy.load('en_core_web_sm')

In [ ]:
# def process_words(tweet):
#     tweet = tweet.lower()
#     shortform = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Bayesian Learning/Project 1/Trial 6/abbreviations.csv')
#     shortform_list = shortform['abbreviation'].tolist()
#     doc = nlp(tweet)

#     # p = []
#     # for i in string.punctuation:
#     # p.append(i)

#     punctuations = [',','!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', ':', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~']

#     tweet_corrected = []
#     #correct spelling in the tweets.

#     #dont touch shortforms
#     for word in doc:
#         if str(word) not in shortform_list:
#             tweet_corrected_word = nlp(str(TextBlob(str(word)).correct()))[0]

#             #doc2 = nlp(tweet_corrected_word)
#             if not (tweet_corrected_word).is_stop:
#                 #print("not stop", tweet_corrected_word)
#                 if((str(tweet_corrected_word)) not in punctuations):
#                      #print("punctionation not found:",tweet_corrected_word)


#                      tweet_corrected.append(tweet_corrected_word.lemma_)


#         else:
#             tweet_corrected.append(str(word))
#             #print("found " ,word)

#     sentence = ' '.join(tweet_corrected)
#     return sentence

In [ ]:
#df.loc[:,'clean_tweet'] = df.loc[:,'tweet w/o user'].progress_apply(process_words)

100%|██████████| 6000/6000 [34:24<00:00,  2.91it/s]
<ipython-input-11-0faf64c04f75>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:,'clean_tweet'] = df.loc[:,'tweet w/o user'].progress_apply(process_words)


In [ ]:
#df.to_csv('trail6_tweets_processed_Mar5th.csv', index=False)

NameError: name 'df' is not defined

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Bayesian Learning/Project 1/Trial 6/trail6_tweets_processed_Mar5th.csv', encoding = 'ISO-8859-1')
df

id   Latitude   Longitude  \
0     USER_131347  25.587695  -80.379636   
1     USER_321775  34.046692 -117.524254   
2     USER_139842  42.286785  -85.590620   
3     USER_362638  39.355249  -76.598514   
4     USER_311240  40.648491  -73.962830   
...           ...        ...         ...   
5995  USER_306230  40.685128  -73.581845   
5996  USER_247488  41.650608  -70.299491   
5997  USER_325702  39.070599  -77.011907   
5998  USER_235606  33.649463  -84.002263   
5999  USER_298845  35.995759  -78.888912   

                                                  tweet  tweet_count  \
0                          @USER_4beb918b followingg (:           24   
1     @USER_c586797f WHATZ GREAT MANN OF GOD, IF YOU...           33   
2     @USER_03159296 I'd have to go with the snow, i...           38   
3                                @USER_bcfa504a yup lol           20   
4                      Ladies be nice. No rude behavior           20   
...                                                 ...          ...   
5995  #beforeidie i wanna hav a family, somethin lik...           75   
5996  @USER_88b09e4d im not trying to ! i told her i...           23   
5997  RT @USER_8bde831b: Almost lunch thank God just...           41   
5998  aaahhh just read @USER_34876f43 dm...where my ...           43   
5999  If I had a girlfriend, she wud have a girlfrie...           25   

                                       tweet_timestamps  \
0     ['23:40:22', '11:39:18', '19:50:35', '21:29:39...   
1     ['22:50:47', '01:10:21', '03:13:05', '03:30:42...   
2     ['23:40:01', '23:42:45', '00:02:50', '00:09:07...   
3     ['16:51:44', '17:40:36', '17:48:26', '17:49:08...   
4     ['23:24:15', '23:56:40', '00:03:54', '02:53:08...   
...                                                 ...   
5995  ['22:58:19', '23:45:29', '00:16:39', '00:18:38...   
5996  ['14:39:16', '14:55:18', '15:03:54', '15:07:45...   
5997  ['22:45:21', '22:47:06', '22:49:13', '22:54:22...   
5998  ['22:43:27', '22:43:47', '22:50:12', '00:55:55...   
5999  ['02:42:09', '03:56:38', '13:24:48', '14:29:09...   

                                         tweet w/o user  \
0                                         followingg (:   
1      WHATZ GREAT MANN OF GOD, IF YOUR NOT FOLLOWIN...   
2      I'd have to go with the snow, it's much cleaner.   
3                                               yup lol   
4                      Ladies be nice. No rude behavior   
...                                                 ...   
5995  #beforeidie i wanna hav a family, somethin lik...   
5996   im not trying to ! i told her id help her its...   
5997  RT : Almost lunch thank God just 5mins left I'...   
5998  aaahhh just read  dm...where my lil bro  at..f...   
5999  If I had a girlfriend, she wud have a girlfrie...   

                                            clean_tweet  
0                                             follow (:  
1       great mann god follow   realise brow get bt ...  
2                                          snow cleaner  
3                                                   lol  
4                               lady nice rude behavior  
...                                                 ...  
5995  beforeidie wanna hav family like hood negro re...  
5996    m try tell d help cuz nick nt kno apologize ...  
5997                  lunch thank god mind leave hungry  
5998  ahahah read   dm ... lil brow   .. fool hit ge...  
5999                  girlfriend wud girlfriend ... lol  

[6000 rows x 8 columns]

In [4]:
tweets = df['clean_tweet']
tweets

0                                               follow (:
1         great mann god follow   realise brow get bt ...
2                                            snow cleaner
3                                                     lol
4                                 lady nice rude behavior
                              ...                        
5995    beforeidie wanna hav family like hood negro re...
5996      m try tell d help cuz nick nt kno apologize ...
5997                    lunch thank god mind leave hungry
5998    ahahah read   dm ... lil brow   .. fool hit ge...
5999                    girlfriend wud girlfriend ... lol
Name: clean_tweet, Length: 6000, dtype: object

In [5]:
tweets = list(tweets)
tweets

['  follow (:',
 '  great mann god follow   realise brow get bt real',
 '  snow cleaner',
 '  lol',
 'lady nice rude behavior',
 '  thank',
 'scott nt know van sunday',
 ' ',
 'follow   fucking good ... creativecontrol.to',
 '  know hata stand phone stick freeze bb lol',
 'ill',
 '  today end 5',
 'recross trill yeathatsmyshit',
 'followsunday      ',
 'x crack dealer click coat da shrill heartless like cold blooded kill filthy dirty da money night ..',
 'hood get ta security walk user pastor get escort church',
 '  send ur pin',
 'drank shout',
 '10 mind ..... ã¢âÂ\x97âÂ\x80---nd jealous',
 'home sweet home ... thank god stay late come home sleep single',
 'lol',
 '  let talk weekend contest ... u say u serve u change ur mind 3 news :(',
 'u sell n bottle live unotmytype',
 '  sure majority',
 '  friday smoke say dat',
 'test 2morrow n friday ugh ..... spring break wood hood ..... get ta work b c hamilton county close school!ll',
 'see ex today .. interesting ..',
 '  vs work caus

In [ ]:
len(tweets)

6000

In [ ]:
def max_words(tweets):
  maxlen = 0
  for sentence in tweets:
    sentence = str(sentence)
    words = sentence.split()
    if len(words)>maxlen:
      maxlen = len(words)

  return maxlen

In [ ]:
print(max_words(tweets))

33


In [6]:
voc_size = 20000

In [ ]:
sent = tweets[1]
print(sent)
words = sent.split()
print(len(words))
sent1 = " ".join(words)
print(sent1)

  great mann god follow   realise brow get bt real
9
great mann god follow realise brow get bt real


In [7]:
sent = tweets[:]
sent

['  follow (:',
 '  great mann god follow   realise brow get bt real',
 '  snow cleaner',
 '  lol',
 'lady nice rude behavior',
 '  thank',
 'scott nt know van sunday',
 ' ',
 'follow   fucking good ... creativecontrol.to',
 '  know hata stand phone stick freeze bb lol',
 'ill',
 '  today end 5',
 'recross trill yeathatsmyshit',
 'followsunday      ',
 'x crack dealer click coat da shrill heartless like cold blooded kill filthy dirty da money night ..',
 'hood get ta security walk user pastor get escort church',
 '  send ur pin',
 'drank shout',
 '10 mind ..... ã¢âÂ\x97âÂ\x80---nd jealous',
 'home sweet home ... thank god stay late come home sleep single',
 'lol',
 '  let talk weekend contest ... u say u serve u change ur mind 3 news :(',
 'u sell n bottle live unotmytype',
 '  sure majority',
 '  friday smoke say dat',
 'test 2morrow n friday ugh ..... spring break wood hood ..... get ta work b c hamilton county close school!ll',
 'see ex today .. interesting ..',
 '  vs work caus

In [8]:
onehot_repr = [one_hot(str(words) , voc_size) for words in sent]
print(onehot_repr)

[[3992], [17236, 3861, 16123, 3992, 3595, 19042, 12143, 15984, 1276], [15691, 3359], [16157], [13448, 17505, 10857, 9125], [5214], [308, 6419, 17036, 19265, 946], [], [3992, 2976, 10852, 5593, 6356], [17036, 4555, 1019, 9314, 14381, 16720, 4098, 16157], [5515], [6904, 14036, 19101], [16191, 18910, 18259], [15379], [10090, 1242, 9729, 1541, 19501, 12953, 8248, 6624, 2997, 12775, 6520, 4028, 2082, 19793, 12953, 10, 17481], [12291, 12143, 13955, 9306, 17461, 6697, 11589, 12143, 19227, 2860], [15026, 5103, 8480], [15875, 13994], [9188, 11537, 8570, 17446, 3539], [1818, 14466, 1818, 5214, 16123, 3996, 15376, 7177, 1818, 18513, 8555], [16157], [4298, 13128, 581, 13856, 6726, 11003, 6726, 11798, 6726, 9950, 5103, 11537, 5727, 14192], [6726, 3751, 1796, 14172, 18827, 1024], [6025, 5613], [4786, 19973, 11003, 15741], [19732, 17283, 1796, 4786, 4730, 16289, 16129, 14486, 12291, 12143, 13955, 7665, 8298, 1884, 7893, 11891, 1738, 2583, 16390], [9746, 12012, 6904, 6347], [13092, 7665, 17261, 18658,

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
sent_length =40
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen = sent_length)
print(embedded_docs)

[[    0     0     0 ...     0     0  3992]
 [    0     0     0 ... 12143 15984  1276]
 [    0     0     0 ...     0 15691  3359]
 ...
 [    0     0     0 ... 11537   994 10573]
 [    0     0     0 ... 10172 12400 10854]
 [    0     0     0 ... 18142 10696 16157]]


In [11]:
 dim =15
 model = Sequential()
 model.add(Embedding(voc_size, dim, input_length = sent_length))
 model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 40, 15)            300000    
                                                                 
Total params: 300000 (1.14 MB)
Trainable params: 300000 (1.14 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

188/188 [==============================] - 0s 1ms/step
[[[ 0.01753366 -0.03800175 -0.04657694 ... -0.04925044  0.01583626
    0.04136897]
  [ 0.01753366 -0.03800175 -0.04657694 ... -0.04925044  0.01583626
    0.04136897]
  [ 0.01753366 -0.03800175 -0.04657694 ... -0.04925044  0.01583626
    0.04136897]
  ...
  [ 0.01753366 -0.03800175 -0.04657694 ... -0.04925044  0.01583626
    0.04136897]
  [ 0.01753366 -0.03800175 -0.04657694 ... -0.04925044  0.01583626
    0.04136897]
  [ 0.02780993  0.01184059  0.0172844  ...  0.02099783 -0.03158937
   -0.03139359]]

 [[ 0.01753366 -0.03800175 -0.04657694 ... -0.04925044  0.01583626
    0.04136897]
  [ 0.01753366 -0.03800175 -0.04657694 ... -0.04925044  0.01583626
    0.04136897]
  [ 0.01753366 -0.03800175 -0.04657694 ... -0.04925044  0.01583626
    0.04136897]
  ...
  [ 0.00450229 -0.03480031 -0.03035741 ...  0.02812458  0.0202446
    0.00777941]
  [ 0.0389935   0.03497175 -0.04755924 ...  0.02405018  0.02946499
    0.01317101]
  [-0.01497812 -0.0

In [ ]:
df

id   Latitude   Longitude  \
0     USER_131347  25.587695  -80.379636   
1     USER_321775  34.046692 -117.524254   
2     USER_139842  42.286785  -85.590620   
3     USER_362638  39.355249  -76.598514   
4     USER_311240  40.648491  -73.962830   
...           ...        ...         ...   
5995  USER_306230  40.685128  -73.581845   
5996  USER_247488  41.650608  -70.299491   
5997  USER_325702  39.070599  -77.011907   
5998  USER_235606  33.649463  -84.002263   
5999  USER_298845  35.995759  -78.888912   

                                                  tweet  tweet_count  \
0                          @USER_4beb918b followingg (:           24   
1     @USER_c586797f WHATZ GREAT MANN OF GOD, IF YOU...           33   
2     @USER_03159296 I'd have to go with the snow, i...           38   
3                                @USER_bcfa504a yup lol           20   
4                      Ladies be nice. No rude behavior           20   
...                                                 ...          ...   
5995  #beforeidie i wanna hav a family, somethin lik...           75   
5996  @USER_88b09e4d im not trying to ! i told her i...           23   
5997  RT @USER_8bde831b: Almost lunch thank God just...           41   
5998  aaahhh just read @USER_34876f43 dm...where my ...           43   
5999  If I had a girlfriend, she wud have a girlfrie...           25   

                                       tweet_timestamps  \
0     ['23:40:22', '11:39:18', '19:50:35', '21:29:39...   
1     ['22:50:47', '01:10:21', '03:13:05', '03:30:42...   
2     ['23:40:01', '23:42:45', '00:02:50', '00:09:07...   
3     ['16:51:44', '17:40:36', '17:48:26', '17:49:08...   
4     ['23:24:15', '23:56:40', '00:03:54', '02:53:08...   
...                                                 ...   
5995  ['22:58:19', '23:45:29', '00:16:39', '00:18:38...   
5996  ['14:39:16', '14:55:18', '15:03:54', '15:07:45...   
5997  ['22:45:21', '22:47:06', '22:49:13', '22:54:22...   
5998  ['22:43:27', '22:43:47', '22:50:12', '00:55:55...   
5999  ['02:42:09', '03:56:38', '13:24:48', '14:29:09...   

                                         tweet w/o user  \
0                                         followingg (:   
1      WHATZ GREAT MANN OF GOD, IF YOUR NOT FOLLOWIN...   
2      I'd have to go with the snow, it's much cleaner.   
3                                               yup lol   
4                      Ladies be nice. No rude behavior   
...                                                 ...   
5995  #beforeidie i wanna hav a family, somethin lik...   
5996   im not trying to ! i told her id help her its...   
5997  RT : Almost lunch thank God just 5mins left I'...   
5998  aaahhh just read  dm...where my lil bro  at..f...   
5999  If I had a girlfriend, she wud have a girlfrie...   

                                            clean_tweet  
0                                             follow (:  
1       great mann god follow   realise brow get bt ...  
2                                          snow cleaner  
3                                                   lol  
4                               lady nice rude behavior  
...                                                 ...  
5995  beforeidie wanna hav family like hood negro re...  
5996    m try tell d help cuz nick nt kno apologize ...  
5997                  lunch thank god mind leave hungry  
5998  ahahah read   dm ... lil brow   .. fool hit ge...  
5999                  girlfriend wud girlfriend ... lol  

[6000 rows x 8 columns]

In [13]:
embedded_matrix = model.predict(embedded_docs)

188/188 [==============================] - 0s 1ms/step


In [14]:
embedded_matrix.shape

(6000, 40, 15)

In [15]:
flattened_embedded_matrix = embedded_matrix.reshape(embedded_matrix.shape[0], -1)
flattened_embedded_matrix

array([[-0.03796331,  0.00524763,  0.03760947, ..., -0.03350747,
        -0.03888482, -0.02270815],
       [-0.03796331,  0.00524763,  0.03760947, ..., -0.00025985,
        -0.03167909,  0.02141967],
       [-0.03796331,  0.00524763,  0.03760947, ...,  0.0482004 ,
         0.01932657,  0.01881416],
       ...,
       [-0.03796331,  0.00524763,  0.03760947, ...,  0.0476457 ,
        -0.02583476, -0.01472222],
       [-0.03796331,  0.00524763,  0.03760947, ..., -0.00158701,
        -0.03411471, -0.03827635],
       [-0.03796331,  0.00524763,  0.03760947, ..., -0.00420956,
        -0.04873065,  0.02694185]], dtype=float32)

In [16]:
flattened_embedded_matrix.shape

(6000, 600)

In [17]:
df

id   Latitude   Longitude  \
0     USER_131347  25.587695  -80.379636   
1     USER_321775  34.046692 -117.524254   
2     USER_139842  42.286785  -85.590620   
3     USER_362638  39.355249  -76.598514   
4     USER_311240  40.648491  -73.962830   
...           ...        ...         ...   
5995  USER_306230  40.685128  -73.581845   
5996  USER_247488  41.650608  -70.299491   
5997  USER_325702  39.070599  -77.011907   
5998  USER_235606  33.649463  -84.002263   
5999  USER_298845  35.995759  -78.888912   

                                                  tweet  tweet_count  \
0                          @USER_4beb918b followingg (:           24   
1     @USER_c586797f WHATZ GREAT MANN OF GOD, IF YOU...           33   
2     @USER_03159296 I'd have to go with the snow, i...           38   
3                                @USER_bcfa504a yup lol           20   
4                      Ladies be nice. No rude behavior           20   
...                                                 ...          ...   
5995  #beforeidie i wanna hav a family, somethin lik...           75   
5996  @USER_88b09e4d im not trying to ! i told her i...           23   
5997  RT @USER_8bde831b: Almost lunch thank God just...           41   
5998  aaahhh just read @USER_34876f43 dm...where my ...           43   
5999  If I had a girlfriend, she wud have a girlfrie...           25   

                                       tweet_timestamps  \
0     ['23:40:22', '11:39:18', '19:50:35', '21:29:39...   
1     ['22:50:47', '01:10:21', '03:13:05', '03:30:42...   
2     ['23:40:01', '23:42:45', '00:02:50', '00:09:07...   
3     ['16:51:44', '17:40:36', '17:48:26', '17:49:08...   
4     ['23:24:15', '23:56:40', '00:03:54', '02:53:08...   
...                                                 ...   
5995  ['22:58:19', '23:45:29', '00:16:39', '00:18:38...   
5996  ['14:39:16', '14:55:18', '15:03:54', '15:07:45...   
5997  ['22:45:21', '22:47:06', '22:49:13', '22:54:22...   
5998  ['22:43:27', '22:43:47', '22:50:12', '00:55:55...   
5999  ['02:42:09', '03:56:38', '13:24:48', '14:29:09...   

                                         tweet w/o user  \
0                                         followingg (:   
1      WHATZ GREAT MANN OF GOD, IF YOUR NOT FOLLOWIN...   
2      I'd have to go with the snow, it's much cleaner.   
3                                               yup lol   
4                      Ladies be nice. No rude behavior   
...                                                 ...   
5995  #beforeidie i wanna hav a family, somethin lik...   
5996   im not trying to ! i told her id help her its...   
5997  RT : Almost lunch thank God just 5mins left I'...   
5998  aaahhh just read  dm...where my lil bro  at..f...   
5999  If I had a girlfriend, she wud have a girlfrie...   

                                            clean_tweet  
0                                             follow (:  
1       great mann god follow   realise brow get bt ...  
2                                          snow cleaner  
3                                                   lol  
4                               lady nice rude behavior  
...                                                 ...  
5995  beforeidie wanna hav family like hood negro re...  
5996    m try tell d help cuz nick nt kno apologize ...  
5997                  lunch thank god mind leave hungry  
5998  ahahah read   dm ... lil brow   .. fool hit ge...  
5999                  girlfriend wud girlfriend ... lol  

[6000 rows x 8 columns]

In [18]:
yfeatures = ['Latitude','Longitude']
y = df[yfeatures]

In [19]:
bin_name = 'bin_'
for i in range(0,24*2):
    #print(i , end=',')
    df.loc[:,bin_name+str(i)] = 0

In [20]:
df

id   Latitude   Longitude  \
0     USER_131347  25.587695  -80.379636   
1     USER_321775  34.046692 -117.524254   
2     USER_139842  42.286785  -85.590620   
3     USER_362638  39.355249  -76.598514   
4     USER_311240  40.648491  -73.962830   
...           ...        ...         ...   
5995  USER_306230  40.685128  -73.581845   
5996  USER_247488  41.650608  -70.299491   
5997  USER_325702  39.070599  -77.011907   
5998  USER_235606  33.649463  -84.002263   
5999  USER_298845  35.995759  -78.888912   

                                                  tweet  tweet_count  \
0                          @USER_4beb918b followingg (:           24   
1     @USER_c586797f WHATZ GREAT MANN OF GOD, IF YOU...           33   
2     @USER_03159296 I'd have to go with the snow, i...           38   
3                                @USER_bcfa504a yup lol           20   
4                      Ladies be nice. No rude behavior           20   
...                                                 ...          ...   
5995  #beforeidie i wanna hav a family, somethin lik...           75   
5996  @USER_88b09e4d im not trying to ! i told her i...           23   
5997  RT @USER_8bde831b: Almost lunch thank God just...           41   
5998  aaahhh just read @USER_34876f43 dm...where my ...           43   
5999  If I had a girlfriend, she wud have a girlfrie...           25   

                                       tweet_timestamps  \
0     ['23:40:22', '11:39:18', '19:50:35', '21:29:39...   
1     ['22:50:47', '01:10:21', '03:13:05', '03:30:42...   
2     ['23:40:01', '23:42:45', '00:02:50', '00:09:07...   
3     ['16:51:44', '17:40:36', '17:48:26', '17:49:08...   
4     ['23:24:15', '23:56:40', '00:03:54', '02:53:08...   
...                                                 ...   
5995  ['22:58:19', '23:45:29', '00:16:39', '00:18:38...   
5996  ['14:39:16', '14:55:18', '15:03:54', '15:07:45...   
5997  ['22:45:21', '22:47:06', '22:49:13', '22:54:22...   
5998  ['22:43:27', '22:43:47', '22:50:12', '00:55:55...   
5999  ['02:42:09', '03:56:38', '13:24:48', '14:29:09...   

                                         tweet w/o user  \
0                                         followingg (:   
1      WHATZ GREAT MANN OF GOD, IF YOUR NOT FOLLOWIN...   
2      I'd have to go with the snow, it's much cleaner.   
3                                               yup lol   
4                      Ladies be nice. No rude behavior   
...                                                 ...   
5995  #beforeidie i wanna hav a family, somethin lik...   
5996   im not trying to ! i told her id help her its...   
5997  RT : Almost lunch thank God just 5mins left I'...   
5998  aaahhh just read  dm...where my lil bro  at..f...   
5999  If I had a girlfriend, she wud have a girlfrie...   

                                            clean_tweet  bin_0  bin_1  ...  \
0                                             follow (:      0      0  ...   
1       great mann god follow   realise brow get bt ...      0      0  ...   
2                                          snow cleaner      0      0  ...   
3                                                   lol      0      0  ...   
4                               lady nice rude behavior      0      0  ...   
...                                                 ...    ...    ...  ...   
5995  beforeidie wanna hav family like hood negro re...      0      0  ...   
5996    m try tell d help cuz nick nt kno apologize ...      0      0  ...   
5997                  lunch thank god mind leave hungry      0      0  ...   
5998  ahahah read   dm ... lil brow   .. fool hit ge...      0      0  ...   
5999                  girlfriend wud girlfriend ... lol      0      0  ...   

      bin_38  bin_39  bin_40  bin_41  bin_42  bin_43  bin_44  bin_45  bin_46  \
0          0       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          0       0      

In [21]:
s = df['tweet_timestamps'].str.split(',')
s
total_rows = df.shape[0]
for row in range(0,total_rows):
    #print(row,end=',')
    for time in s[row]:
        list_hour = time.split(':')[0]
        list_hour = re.findall('[0-9]+'  ,list_hour)
        hour_bin = int(list_hour[0])
        minute = int(time.split(':')[1])
        if(minute<29):
            minute_bin=0
        else:
            minute_bin = 1

        bin_number = 'bin_'+ str(hour_bin*2 + minute_bin)
        df.loc[row,bin_number] = df.loc[row,bin_number] + 1

In [22]:
df

id   Latitude   Longitude  \
0     USER_131347  25.587695  -80.379636   
1     USER_321775  34.046692 -117.524254   
2     USER_139842  42.286785  -85.590620   
3     USER_362638  39.355249  -76.598514   
4     USER_311240  40.648491  -73.962830   
...           ...        ...         ...   
5995  USER_306230  40.685128  -73.581845   
5996  USER_247488  41.650608  -70.299491   
5997  USER_325702  39.070599  -77.011907   
5998  USER_235606  33.649463  -84.002263   
5999  USER_298845  35.995759  -78.888912   

                                                  tweet  tweet_count  \
0                          @USER_4beb918b followingg (:           24   
1     @USER_c586797f WHATZ GREAT MANN OF GOD, IF YOU...           33   
2     @USER_03159296 I'd have to go with the snow, i...           38   
3                                @USER_bcfa504a yup lol           20   
4                      Ladies be nice. No rude behavior           20   
...                                                 ...          ...   
5995  #beforeidie i wanna hav a family, somethin lik...           75   
5996  @USER_88b09e4d im not trying to ! i told her i...           23   
5997  RT @USER_8bde831b: Almost lunch thank God just...           41   
5998  aaahhh just read @USER_34876f43 dm...where my ...           43   
5999  If I had a girlfriend, she wud have a girlfrie...           25   

                                       tweet_timestamps  \
0     ['23:40:22', '11:39:18', '19:50:35', '21:29:39...   
1     ['22:50:47', '01:10:21', '03:13:05', '03:30:42...   
2     ['23:40:01', '23:42:45', '00:02:50', '00:09:07...   
3     ['16:51:44', '17:40:36', '17:48:26', '17:49:08...   
4     ['23:24:15', '23:56:40', '00:03:54', '02:53:08...   
...                                                 ...   
5995  ['22:58:19', '23:45:29', '00:16:39', '00:18:38...   
5996  ['14:39:16', '14:55:18', '15:03:54', '15:07:45...   
5997  ['22:45:21', '22:47:06', '22:49:13', '22:54:22...   
5998  ['22:43:27', '22:43:47', '22:50:12', '00:55:55...   
5999  ['02:42:09', '03:56:38', '13:24:48', '14:29:09...   

                                         tweet w/o user  \
0                                         followingg (:   
1      WHATZ GREAT MANN OF GOD, IF YOUR NOT FOLLOWIN...   
2      I'd have to go with the snow, it's much cleaner.   
3                                               yup lol   
4                      Ladies be nice. No rude behavior   
...                                                 ...   
5995  #beforeidie i wanna hav a family, somethin lik...   
5996   im not trying to ! i told her id help her its...   
5997  RT : Almost lunch thank God just 5mins left I'...   
5998  aaahhh just read  dm...where my lil bro  at..f...   
5999  If I had a girlfriend, she wud have a girlfrie...   

                                            clean_tweet  bin_0  bin_1  ...  \
0                                             follow (:      2      1  ...   
1       great mann god follow   realise brow get bt ...      1      1  ...   
2                                          snow cleaner      3      0  ...   
3                                                   lol      0      0  ...   
4                               lady nice rude behavior      2      0  ...   
...                                                 ...    ...    ...  ...   
5995  beforeidie wanna hav family like hood negro re...      2      2  ...   
5996    m try tell d help cuz nick nt kno apologize ...      0      0  ...   
5997                  lunch thank god mind leave hungry      1      4  ...   
5998  ahahah read   dm ... lil brow   .. fool hit ge...      0      2  ...   
5999                  girlfriend wud girlfriend ... lol      0      0  ...   

      bin_38  bin_39  bin_40  bin_41  bin_42  bin_43  bin_44  bin_45  bin_46  \
0          0       4       0       1       1       2       1       0       1   
1          1       4       1       3       1       0       2       3       1   
2          3       0      

In [23]:
xfeatures = ['tweet_count', 'bin_0', 'bin_1', 'bin_2', 'bin_3',
       'bin_4', 'bin_5', 'bin_6', 'bin_7', 'bin_8', 'bin_9', 'bin_10',
       'bin_11', 'bin_12', 'bin_13', 'bin_14', 'bin_15', 'bin_16', 'bin_17',
       'bin_18', 'bin_19', 'bin_20', 'bin_21', 'bin_22', 'bin_23', 'bin_24',
       'bin_25', 'bin_26', 'bin_27', 'bin_28', 'bin_29', 'bin_30', 'bin_31',
       'bin_32', 'bin_33', 'bin_34', 'bin_35', 'bin_36', 'bin_37', 'bin_38',
       'bin_39', 'bin_40', 'bin_41', 'bin_42', 'bin_43', 'bin_44', 'bin_45',
       'bin_46', 'bin_47']
yfeatures = ['Latitude','Longitude']

In [24]:
X = df[xfeatures]
y = df[yfeatures]

In [29]:
X_np = X.values
X

tweet_count  bin_0  bin_1  bin_2  bin_3  bin_4  bin_5  bin_6  bin_7  \
0              24      2      1      1      0      0      0      0      0   
1              33      1      1      1      0      0      0      1      1   
2              38      3      0      2      0      3      4      1      0   
3              20      0      0      0      0      1      0      0      0   
4              20      2      0      1      0      0      2      0      2   
...           ...    ...    ...    ...    ...    ...    ...    ...    ...   
5995           75      2      2      1      6      7      6      1      2   
5996           23      0      0      0      2      0      0      0      0   
5997           41      1      4      1      1      2      1      2      1   
5998           43      0      2      4      1      2      0      0      0   
5999           25      0      0      0      0      0      1      0      1   

      bin_8  ...  bin_38  bin_39  bin_40  bin_41  bin_42  bin_43  bin_44  \
0         0  ...       0       4       0       1       1       2       1   
1         0  ...       1       4       1       3       1       0       2   
2         2  ...       3       0       0       1       0       1       0   
3         0  ...       2       0       0       0       0       0       0   
4         1  ...       0       2       0       0       1       0       1   
...     ...  ...     ...     ...     ...     ...     ...     ...     ...   
5995      1  ...       1       0       1       1       1       0       0   
5996      0  ...       0       0       3       2       4       3       3   
5997      2  ...       0       1       0       3       1       0       0   
5998      0  ...       2       0       0       0       1       0       0   
5999      2  ...       0       0       0       1       0       0       0   

      bin_45  bin_46  bin_47  
0          0       1       2  
1          3       1       1  
2          1       0       3  
3          0       0       0  
4          0       1       1  
...      ...     ...     ...  
5995       1       0       6  
5996       0       0       0  
5997       5       0       2  
5998       3       0       0  
5999       0       0       0  

[6000 rows x 49 columns]

In [33]:
final_X_np = np.concatenate((X_np, flattened_embedded_matrix), axis=1)
final_X_np

array([[ 2.40000000e+01,  2.00000000e+00,  1.00000000e+00, ...,
        -3.35074663e-02, -3.88848186e-02, -2.27081534e-02],
       [ 3.30000000e+01,  1.00000000e+00,  1.00000000e+00, ...,
        -2.59853899e-04, -3.16790938e-02,  2.14196704e-02],
       [ 3.80000000e+01,  3.00000000e+00,  0.00000000e+00, ...,
         4.82004024e-02,  1.93265714e-02,  1.88141577e-02],
       ...,
       [ 4.10000000e+01,  1.00000000e+00,  4.00000000e+00, ...,
         4.76456992e-02, -2.58347634e-02, -1.47222169e-02],
       [ 4.30000000e+01,  0.00000000e+00,  2.00000000e+00, ...,
        -1.58701092e-03, -3.41147073e-02, -3.82763520e-02],
       [ 2.50000000e+01,  0.00000000e+00,  0.00000000e+00, ...,
        -4.20955569e-03, -4.87306491e-02,  2.69418471e-02]])

In [44]:
final_X_np[0][:50]

array([24.        ,  2.        ,  1.        ,  1.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  2.        ,
        0.        ,  0.        ,  1.        ,  1.        ,  0.        ,
        0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
        0.        ,  1.        ,  1.        ,  0.        ,  0.        ,
        4.        ,  0.        ,  1.        ,  1.        ,  2.        ,
        1.        ,  0.        ,  1.        ,  2.        , -0.03796331])

In [37]:
y_np = y.values

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(final_X_np, y_np, test_size=0.2, random_state=42)

In [45]:
scale_columns = X_train[:,:49]
print(scale_columns[0])

[44.  2.  3.  0.  8. 10.  5.  1.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  2.  0.  0.  0.  0.  0.
  0.  1.  3.  0.  0.  0.  0.  1.  0.  2.  0.  2.  0.]


In [46]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scale_columns_after = scaler.fit_transform(scale_columns)
scale_columns_after[0]

array([0.08540925, 0.125     , 0.21428571, 0.        , 0.66666667,
       0.71428571, 0.23809524, 0.05555556, 0.        , 0.05882353,
       0.        , 0.        , 0.        , 0.        , 0.05555556,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07692308, 0.07692308,
       0.15384615, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07692308, 0.15      , 0.        ,
       0.        , 0.        , 0.        , 0.07142857, 0.        ,
       0.13333333, 0.        , 0.125     , 0.        ])

In [50]:
X_train[:, :49] = scale_columns_after

In [52]:
scale_columns_test = X_test[:,:49]
scale_columns_after_test = scaler.transform(scale_columns_test)
scale_columns_after_test[0]

array([0.0747331 , 0.0625    , 0.07142857, 0.        , 0.        ,
       0.14285714, 0.04761905, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.0952381 , 0.05555556,
       0.        , 0.        , 0.07142857, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.46153846, 0.25      , 0.16666667,
       0.        , 0.45454545, 0.2       , 0.07142857, 0.14285714,
       0.06666667, 0.        , 0.25      , 0.08333333])

In [53]:
X_test[:, :49] = scale_columns_after_test

In [55]:
X_train.shape[1]

649

In [62]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Define your ANN model
model = Sequential([
    Dense(649, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(2)  # Output layer with 2 neurons for latitude and longitude prediction
])

# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Print the model summary
model.summary()

# Fit the model to the training data
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

mse, mae = model.evaluate(X_test, y_test)
print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_37 (Dense)            (None, 649)               421850    
                                                                 
 dense_38 (Dense)            (None, 128)               83200     
                                                                 
 dense_39 (Dense)            (None, 64)                8256      
                                                                 
 dense_40 (Dense)            (None, 32)                2080      
                                                                 
 dense_41 (Dense)            (None, 16)                528       
                                                                 
 dense_42 (Dense)            (None, 2)                 34        
                                                                 
Total params: 515948 (1.97 MB)
Trainable params: 51594

In [ ]:
#128,64,32,16 ---> 138mse

In [67]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error

# Define the XGBoost model
xgb_model = xgb.XGBRegressor(objective ='reg:squarederror',
                             colsample_bytree = 0.3,
                             learning_rate = 0.1,
                             max_depth = 3,
                             alpha = 10,
                             n_estimators = 100)  # You can adjust hyperparameters as needed

# Train the model
xgb_model.fit(X_train, y_train)

# Make predictions on the test data
y_pred_xgb = xgb_model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred_xgb)
print("Mean Squared Error:", mse)

Mean Squared Error: 136.84967058037873
