In [1]:
import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.text import one_hot
import re

In [3]:
from tqdm import tqdm
tqdm.pandas()

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# twitter_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Bayesian Learning/Project 1/Trial 5/train.csv', encoding = 'ISO-8859-1')
# df = twitter_data.iloc[:6000]
# df.head()

id   Latitude   Longitude  \
0  USER_131347  25.587695  -80.379636   
1  USER_321775  34.046692 -117.524254   
2  USER_139842  42.286785  -85.590620   
3  USER_362638  39.355249  -76.598514   
4  USER_311240  40.648491  -73.962830   

                                               tweet  tweet_count  \
0                       @USER_4beb918b followingg (:           24   
1  @USER_c586797f WHATZ GREAT MANN OF GOD, IF YOU...           33   
2  @USER_03159296 I'd have to go with the snow, i...           38   
3                             @USER_bcfa504a yup lol           20   
4                   Ladies be nice. No rude behavior           20   

                                    tweet_timestamps  
0  ['23:40:22', '11:39:18', '19:50:35', '21:29:39...  
1  ['22:50:47', '01:10:21', '03:13:05', '03:30:42...  
2  ['23:40:01', '23:42:45', '00:02:50', '00:09:07...  
3  ['16:51:44', '17:40:36', '17:48:26', '17:49:08...  
4  ['23:24:15', '23:56:40', '00:03:54', '02:53:08...

In [ ]:
# def remove_user_tweet(tweet):
#     pattern = '[@][a-zA-Z0-9_]*'
#     #matches = re.findall(pattern  ,tweet)
#     match = re.compile( '[@][a-zA-Z0-9_]*')
#     sentence = match.sub('', tweet)
#     return sentence

In [ ]:
#df.loc[:,'tweet w/o user'] = df.loc[:,'tweet'].apply(remove_user_tweet)

<ipython-input-4-8ec2d1654db1>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:,'tweet w/o user'] = df.loc[:,'tweet'].apply(remove_user_tweet)


In [ ]:
# df

id   Latitude   Longitude  \
0     USER_131347  25.587695  -80.379636   
1     USER_321775  34.046692 -117.524254   
2     USER_139842  42.286785  -85.590620   
3     USER_362638  39.355249  -76.598514   
4     USER_311240  40.648491  -73.962830   
...           ...        ...         ...   
5995  USER_306230  40.685128  -73.581845   
5996  USER_247488  41.650608  -70.299491   
5997  USER_325702  39.070599  -77.011907   
5998  USER_235606  33.649463  -84.002263   
5999  USER_298845  35.995759  -78.888912   

                                                  tweet  tweet_count  \
0                          @USER_4beb918b followingg (:           24   
1     @USER_c586797f WHATZ GREAT MANN OF GOD, IF YOU...           33   
2     @USER_03159296 I'd have to go with the snow, i...           38   
3                                @USER_bcfa504a yup lol           20   
4                      Ladies be nice. No rude behavior           20   
...                                                 ...          ...   
5995  #beforeidie i wanna hav a family, somethin lik...           75   
5996  @USER_88b09e4d im not trying to ! i told her i...           23   
5997  RT @USER_8bde831b: Almost lunch thank God just...           41   
5998  aaahhh just read @USER_34876f43 dm...where my ...           43   
5999  If I had a girlfriend, she wud have a girlfrie...           25   

                                       tweet_timestamps  \
0     ['23:40:22', '11:39:18', '19:50:35', '21:29:39...   
1     ['22:50:47', '01:10:21', '03:13:05', '03:30:42...   
2     ['23:40:01', '23:42:45', '00:02:50', '00:09:07...   
3     ['16:51:44', '17:40:36', '17:48:26', '17:49:08...   
4     ['23:24:15', '23:56:40', '00:03:54', '02:53:08...   
...                                                 ...   
5995  ['22:58:19', '23:45:29', '00:16:39', '00:18:38...   
5996  ['14:39:16', '14:55:18', '15:03:54', '15:07:45...   
5997  ['22:45:21', '22:47:06', '22:49:13', '22:54:22...   
5998  ['22:43:27', '22:43:47', '22:50:12', '00:55:55...   
5999  ['02:42:09', '03:56:38', '13:24:48', '14:29:09...   

                                         tweet w/o user  
0                                         followingg (:  
1      WHATZ GREAT MANN OF GOD, IF YOUR NOT FOLLOWIN...  
2      I'd have to go with the snow, it's much cleaner.  
3                                               yup lol  
4                      Ladies be nice. No rude behavior  
...                                                 ...  
5995  #beforeidie i wanna hav a family, somethin lik...  
5996   im not trying to ! i told her id help her its...  
5997  RT : Almost lunch thank God just 5mins left I'...  
5998  aaahhh just read  dm...where my lil bro  at..f...  
5999  If I had a girlfriend, she wud have a girlfrie...  

[6000 rows x 7 columns]

In [ ]:
# import pandas as pd
# import re
# import nltk
# import spacy
# import numpy as np
# from textblob import TextBlob
# import gensim
# nlp = spacy.load('en_core_web_sm')

In [ ]:
# def process_words(tweet):
#     tweet = tweet.lower()
#     shortform = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Bayesian Learning/Project 1/Trial 6/abbreviations.csv')
#     shortform_list = shortform['abbreviation'].tolist()
#     doc = nlp(tweet)

#     # p = []
#     # for i in string.punctuation:
#     # p.append(i)

#     punctuations = [',','!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', ':', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~']

#     tweet_corrected = []
#     #correct spelling in the tweets.

#     #dont touch shortforms
#     for word in doc:
#         if str(word) not in shortform_list:
#             tweet_corrected_word = nlp(str(TextBlob(str(word)).correct()))[0]

#             #doc2 = nlp(tweet_corrected_word)
#             if not (tweet_corrected_word).is_stop:
#                 #print("not stop", tweet_corrected_word)
#                 if((str(tweet_corrected_word)) not in punctuations):
#                      #print("punctionation not found:",tweet_corrected_word)


#                      tweet_corrected.append(tweet_corrected_word.lemma_)


#         else:
#             tweet_corrected.append(str(word))
#             #print("found " ,word)

#     sentence = ' '.join(tweet_corrected)
#     return sentence

In [ ]:
#df.loc[:,'clean_tweet'] = df.loc[:,'tweet w/o user'].progress_apply(process_words)

100%|██████████| 6000/6000 [34:24<00:00,  2.91it/s]
<ipython-input-11-0faf64c04f75>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:,'clean_tweet'] = df.loc[:,'tweet w/o user'].progress_apply(process_words)


In [ ]:
#df.to_csv('trail6_tweets_processed_Mar5th.csv', index=False)

NameError: name 'df' is not defined

In [57]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Bayesian Learning/Project 1/Trial 6/trail6_tweets_processed_Mar5th.csv', encoding = 'ISO-8859-1')
df

id   Latitude   Longitude  \
0     USER_131347  25.587695  -80.379636   
1     USER_321775  34.046692 -117.524254   
2     USER_139842  42.286785  -85.590620   
3     USER_362638  39.355249  -76.598514   
4     USER_311240  40.648491  -73.962830   
...           ...        ...         ...   
5995  USER_306230  40.685128  -73.581845   
5996  USER_247488  41.650608  -70.299491   
5997  USER_325702  39.070599  -77.011907   
5998  USER_235606  33.649463  -84.002263   
5999  USER_298845  35.995759  -78.888912   

                                                  tweet  tweet_count  \
0                          @USER_4beb918b followingg (:           24   
1     @USER_c586797f WHATZ GREAT MANN OF GOD, IF YOU...           33   
2     @USER_03159296 I'd have to go with the snow, i...           38   
3                                @USER_bcfa504a yup lol           20   
4                      Ladies be nice. No rude behavior           20   
...                                                 ...          ...   
5995  #beforeidie i wanna hav a family, somethin lik...           75   
5996  @USER_88b09e4d im not trying to ! i told her i...           23   
5997  RT @USER_8bde831b: Almost lunch thank God just...           41   
5998  aaahhh just read @USER_34876f43 dm...where my ...           43   
5999  If I had a girlfriend, she wud have a girlfrie...           25   

                                       tweet_timestamps  \
0     ['23:40:22', '11:39:18', '19:50:35', '21:29:39...   
1     ['22:50:47', '01:10:21', '03:13:05', '03:30:42...   
2     ['23:40:01', '23:42:45', '00:02:50', '00:09:07...   
3     ['16:51:44', '17:40:36', '17:48:26', '17:49:08...   
4     ['23:24:15', '23:56:40', '00:03:54', '02:53:08...   
...                                                 ...   
5995  ['22:58:19', '23:45:29', '00:16:39', '00:18:38...   
5996  ['14:39:16', '14:55:18', '15:03:54', '15:07:45...   
5997  ['22:45:21', '22:47:06', '22:49:13', '22:54:22...   
5998  ['22:43:27', '22:43:47', '22:50:12', '00:55:55...   
5999  ['02:42:09', '03:56:38', '13:24:48', '14:29:09...   

                                         tweet w/o user  \
0                                         followingg (:   
1      WHATZ GREAT MANN OF GOD, IF YOUR NOT FOLLOWIN...   
2      I'd have to go with the snow, it's much cleaner.   
3                                               yup lol   
4                      Ladies be nice. No rude behavior   
...                                                 ...   
5995  #beforeidie i wanna hav a family, somethin lik...   
5996   im not trying to ! i told her id help her its...   
5997  RT : Almost lunch thank God just 5mins left I'...   
5998  aaahhh just read  dm...where my lil bro  at..f...   
5999  If I had a girlfriend, she wud have a girlfrie...   

                                            clean_tweet  
0                                             follow (:  
1       great mann god follow   realise brow get bt ...  
2                                          snow cleaner  
3                                                   lol  
4                               lady nice rude behavior  
...                                                 ...  
5995  beforeidie wanna hav family like hood negro re...  
5996    m try tell d help cuz nick nt kno apologize ...  
5997                  lunch thank god mind leave hungry  
5998  ahahah read   dm ... lil brow   .. fool hit ge...  
5999                  girlfriend wud girlfriend ... lol  

[6000 rows x 8 columns]

In [58]:
tweets = df['clean_tweet']
tweets

0                                               follow (:
1         great mann god follow   realise brow get bt ...
2                                            snow cleaner
3                                                     lol
4                                 lady nice rude behavior
                              ...                        
5995    beforeidie wanna hav family like hood negro re...
5996      m try tell d help cuz nick nt kno apologize ...
5997                    lunch thank god mind leave hungry
5998    ahahah read   dm ... lil brow   .. fool hit ge...
5999                    girlfriend wud girlfriend ... lol
Name: clean_tweet, Length: 6000, dtype: object

In [59]:
tweets = list(tweets)
tweets

['  follow (:',
 '  great mann god follow   realise brow get bt real',
 '  snow cleaner',
 '  lol',
 'lady nice rude behavior',
 '  thank',
 'scott nt know van sunday',
 ' ',
 'follow   fucking good ... creativecontrol.to',
 '  know hata stand phone stick freeze bb lol',
 'ill',
 '  today end 5',
 'recross trill yeathatsmyshit',
 'followsunday      ',
 'x crack dealer click coat da shrill heartless like cold blooded kill filthy dirty da money night ..',
 'hood get ta security walk user pastor get escort church',
 '  send ur pin',
 'drank shout',
 '10 mind ..... ã¢âÂ\x97âÂ\x80---nd jealous',
 'home sweet home ... thank god stay late come home sleep single',
 'lol',
 '  let talk weekend contest ... u say u serve u change ur mind 3 news :(',
 'u sell n bottle live unotmytype',
 '  sure majority',
 '  friday smoke say dat',
 'test 2morrow n friday ugh ..... spring break wood hood ..... get ta work b c hamilton county close school!ll',
 'see ex today .. interesting ..',
 '  vs work caus

In [ ]:
len(tweets)

6000

In [ ]:
def max_words(tweets):
  maxlen = 0
  for sentence in tweets:
    sentence = str(sentence)
    words = sentence.split()
    if len(words)>maxlen:
      maxlen = len(words)

  return maxlen

In [ ]:
print(max_words(tweets))

33


In [60]:
voc_size = 20000

In [ ]:
sent = tweets[1]
print(sent)
words = sent.split()
print(len(words))
sent1 = " ".join(words)
print(sent1)

  great mann god follow   realise brow get bt real
9
great mann god follow realise brow get bt real


In [61]:
sent = tweets[:]
sent

['  follow (:',
 '  great mann god follow   realise brow get bt real',
 '  snow cleaner',
 '  lol',
 'lady nice rude behavior',
 '  thank',
 'scott nt know van sunday',
 ' ',
 'follow   fucking good ... creativecontrol.to',
 '  know hata stand phone stick freeze bb lol',
 'ill',
 '  today end 5',
 'recross trill yeathatsmyshit',
 'followsunday      ',
 'x crack dealer click coat da shrill heartless like cold blooded kill filthy dirty da money night ..',
 'hood get ta security walk user pastor get escort church',
 '  send ur pin',
 'drank shout',
 '10 mind ..... ã¢âÂ\x97âÂ\x80---nd jealous',
 'home sweet home ... thank god stay late come home sleep single',
 'lol',
 '  let talk weekend contest ... u say u serve u change ur mind 3 news :(',
 'u sell n bottle live unotmytype',
 '  sure majority',
 '  friday smoke say dat',
 'test 2morrow n friday ugh ..... spring break wood hood ..... get ta work b c hamilton county close school!ll',
 'see ex today .. interesting ..',
 '  vs work caus

In [62]:
onehot_repr = [one_hot(str(words) , voc_size) for words in sent]
print(onehot_repr)

[[8950], [401, 1040, 14414, 8950, 10580, 2658, 9612, 2104, 16458], [17838, 15020], [10884], [1000, 17824, 13753, 12694], [14045], [3420, 10074, 6191, 3009, 1619], [], [8950, 492, 1871, 1959, 6738], [6191, 2227, 9383, 15694, 766, 19083, 16001, 10884], [14227], [19229, 1289, 12093], [7363, 15449, 5246], [19528], [14438, 6033, 13657, 10252, 6732, 12438, 12846, 5466, 17518, 11168, 9857, 3415, 5104, 9344, 12438, 7428, 10466], [19094, 9612, 18906, 15773, 9897, 12145, 3017, 9612, 2985, 12365], [7107, 13390, 3133], [15622, 17839], [657, 6086, 6548, 12942, 8710], [14906, 673, 14906, 14045, 14414, 4927, 5103, 14894, 14906, 19012, 8385], [10884], [5515, 484, 12882, 16766, 16069, 14213, 16069, 14121, 16069, 10327, 13390, 6086, 11540, 15341], [16069, 13849, 14180, 18773, 6728, 19990], [7891, 3035], [5330, 9472, 14213, 15606], [14724, 4067, 14180, 5330, 13534, 18954, 7241, 13936, 19094, 9612, 18906, 15638, 10439, 15469, 18033, 10071, 964, 8610, 7815], [17232, 3576, 19229, 6991], [15560, 15638, 7369,

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [63]:
sent_length =40
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen = sent_length)
print(embedded_docs)

[[    0     0     0 ...     0     0  8950]
 [    0     0     0 ...  9612  2104 16458]
 [    0     0     0 ...     0 17838 15020]
 ...
 [    0     0     0 ...  6086 15046  2551]
 [    0     0     0 ...  6087 18602 10896]
 [    0     0     0 ...   989  3865 10884]]


In [64]:
 dim =10
 model_emb = Sequential()
 model_emb.add(Embedding(voc_size, dim, input_length = sent_length))
 model_emb.compile('adam','mse')

In [65]:
model_emb.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 40, 10)            200000    
                                                                 
Total params: 200000 (781.25 KB)
Trainable params: 200000 (781.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [66]:
print(model_emb.predict(embedded_docs))

188/188 [==============================] - 2s 9ms/step
[[[ 0.04798564 -0.03601354  0.02113457 ...  0.00036007  0.02901674
    0.01322335]
  [ 0.04798564 -0.03601354  0.02113457 ...  0.00036007  0.02901674
    0.01322335]
  [ 0.04798564 -0.03601354  0.02113457 ...  0.00036007  0.02901674
    0.01322335]
  ...
  [ 0.04798564 -0.03601354  0.02113457 ...  0.00036007  0.02901674
    0.01322335]
  [ 0.04798564 -0.03601354  0.02113457 ...  0.00036007  0.02901674
    0.01322335]
  [-0.03325741 -0.00312737 -0.03582869 ... -0.02402564  0.04662713
    0.00184296]]

 [[ 0.04798564 -0.03601354  0.02113457 ...  0.00036007  0.02901674
    0.01322335]
  [ 0.04798564 -0.03601354  0.02113457 ...  0.00036007  0.02901674
    0.01322335]
  [ 0.04798564 -0.03601354  0.02113457 ...  0.00036007  0.02901674
    0.01322335]
  ...
  [ 0.02920121 -0.02370334  0.0338713  ...  0.01013697 -0.02666342
    0.0331731 ]
  [ 0.00267618 -0.00583182 -0.01169121 ... -0.00934453 -0.01319219
   -0.00270195]
  [-0.00987564 -0.

In [67]:
df

id   Latitude   Longitude  \
0     USER_131347  25.587695  -80.379636   
1     USER_321775  34.046692 -117.524254   
2     USER_139842  42.286785  -85.590620   
3     USER_362638  39.355249  -76.598514   
4     USER_311240  40.648491  -73.962830   
...           ...        ...         ...   
5995  USER_306230  40.685128  -73.581845   
5996  USER_247488  41.650608  -70.299491   
5997  USER_325702  39.070599  -77.011907   
5998  USER_235606  33.649463  -84.002263   
5999  USER_298845  35.995759  -78.888912   

                                                  tweet  tweet_count  \
0                          @USER_4beb918b followingg (:           24   
1     @USER_c586797f WHATZ GREAT MANN OF GOD, IF YOU...           33   
2     @USER_03159296 I'd have to go with the snow, i...           38   
3                                @USER_bcfa504a yup lol           20   
4                      Ladies be nice. No rude behavior           20   
...                                                 ...          ...   
5995  #beforeidie i wanna hav a family, somethin lik...           75   
5996  @USER_88b09e4d im not trying to ! i told her i...           23   
5997  RT @USER_8bde831b: Almost lunch thank God just...           41   
5998  aaahhh just read @USER_34876f43 dm...where my ...           43   
5999  If I had a girlfriend, she wud have a girlfrie...           25   

                                       tweet_timestamps  \
0     ['23:40:22', '11:39:18', '19:50:35', '21:29:39...   
1     ['22:50:47', '01:10:21', '03:13:05', '03:30:42...   
2     ['23:40:01', '23:42:45', '00:02:50', '00:09:07...   
3     ['16:51:44', '17:40:36', '17:48:26', '17:49:08...   
4     ['23:24:15', '23:56:40', '00:03:54', '02:53:08...   
...                                                 ...   
5995  ['22:58:19', '23:45:29', '00:16:39', '00:18:38...   
5996  ['14:39:16', '14:55:18', '15:03:54', '15:07:45...   
5997  ['22:45:21', '22:47:06', '22:49:13', '22:54:22...   
5998  ['22:43:27', '22:43:47', '22:50:12', '00:55:55...   
5999  ['02:42:09', '03:56:38', '13:24:48', '14:29:09...   

                                         tweet w/o user  \
0                                         followingg (:   
1      WHATZ GREAT MANN OF GOD, IF YOUR NOT FOLLOWIN...   
2      I'd have to go with the snow, it's much cleaner.   
3                                               yup lol   
4                      Ladies be nice. No rude behavior   
...                                                 ...   
5995  #beforeidie i wanna hav a family, somethin lik...   
5996   im not trying to ! i told her id help her its...   
5997  RT : Almost lunch thank God just 5mins left I'...   
5998  aaahhh just read  dm...where my lil bro  at..f...   
5999  If I had a girlfriend, she wud have a girlfrie...   

                                            clean_tweet  
0                                             follow (:  
1       great mann god follow   realise brow get bt ...  
2                                          snow cleaner  
3                                                   lol  
4                               lady nice rude behavior  
...                                                 ...  
5995  beforeidie wanna hav family like hood negro re...  
5996    m try tell d help cuz nick nt kno apologize ...  
5997                  lunch thank god mind leave hungry  
5998  ahahah read   dm ... lil brow   .. fool hit ge...  
5999                  girlfriend wud girlfriend ... lol  

[6000 rows x 8 columns]

In [68]:
embedded_matrix = model_emb.predict(embedded_docs)

188/188 [==============================] - 0s 1ms/step


In [69]:
embedded_matrix.shape

(6000, 40, 10)

In [70]:
flattened_embedded_matrix = embedded_matrix.reshape(embedded_matrix.shape[0], -1)
flattened_embedded_matrix

array([[ 0.04798564, -0.03601354,  0.02113457, ..., -0.02402564,
         0.04662713,  0.00184296],
       [ 0.04798564, -0.03601354,  0.02113457, ..., -0.03170357,
         0.03734517, -0.03714806],
       [ 0.04798564, -0.03601354,  0.02113457, ..., -0.01922579,
         0.03755868, -0.0360031 ],
       ...,
       [ 0.04798564, -0.03601354,  0.02113457, ...,  0.02793095,
         0.04043317, -0.00927956],
       [ 0.04798564, -0.03601354,  0.02113457, ...,  0.03979783,
         0.04460337, -0.01676905],
       [ 0.04798564, -0.03601354,  0.02113457, ...,  0.04913798,
         0.00028618,  0.00600382]], dtype=float32)

In [71]:
flattened_embedded_matrix.shape

(6000, 400)

In [72]:
df

id   Latitude   Longitude  \
0     USER_131347  25.587695  -80.379636   
1     USER_321775  34.046692 -117.524254   
2     USER_139842  42.286785  -85.590620   
3     USER_362638  39.355249  -76.598514   
4     USER_311240  40.648491  -73.962830   
...           ...        ...         ...   
5995  USER_306230  40.685128  -73.581845   
5996  USER_247488  41.650608  -70.299491   
5997  USER_325702  39.070599  -77.011907   
5998  USER_235606  33.649463  -84.002263   
5999  USER_298845  35.995759  -78.888912   

                                                  tweet  tweet_count  \
0                          @USER_4beb918b followingg (:           24   
1     @USER_c586797f WHATZ GREAT MANN OF GOD, IF YOU...           33   
2     @USER_03159296 I'd have to go with the snow, i...           38   
3                                @USER_bcfa504a yup lol           20   
4                      Ladies be nice. No rude behavior           20   
...                                                 ...          ...   
5995  #beforeidie i wanna hav a family, somethin lik...           75   
5996  @USER_88b09e4d im not trying to ! i told her i...           23   
5997  RT @USER_8bde831b: Almost lunch thank God just...           41   
5998  aaahhh just read @USER_34876f43 dm...where my ...           43   
5999  If I had a girlfriend, she wud have a girlfrie...           25   

                                       tweet_timestamps  \
0     ['23:40:22', '11:39:18', '19:50:35', '21:29:39...   
1     ['22:50:47', '01:10:21', '03:13:05', '03:30:42...   
2     ['23:40:01', '23:42:45', '00:02:50', '00:09:07...   
3     ['16:51:44', '17:40:36', '17:48:26', '17:49:08...   
4     ['23:24:15', '23:56:40', '00:03:54', '02:53:08...   
...                                                 ...   
5995  ['22:58:19', '23:45:29', '00:16:39', '00:18:38...   
5996  ['14:39:16', '14:55:18', '15:03:54', '15:07:45...   
5997  ['22:45:21', '22:47:06', '22:49:13', '22:54:22...   
5998  ['22:43:27', '22:43:47', '22:50:12', '00:55:55...   
5999  ['02:42:09', '03:56:38', '13:24:48', '14:29:09...   

                                         tweet w/o user  \
0                                         followingg (:   
1      WHATZ GREAT MANN OF GOD, IF YOUR NOT FOLLOWIN...   
2      I'd have to go with the snow, it's much cleaner.   
3                                               yup lol   
4                      Ladies be nice. No rude behavior   
...                                                 ...   
5995  #beforeidie i wanna hav a family, somethin lik...   
5996   im not trying to ! i told her id help her its...   
5997  RT : Almost lunch thank God just 5mins left I'...   
5998  aaahhh just read  dm...where my lil bro  at..f...   
5999  If I had a girlfriend, she wud have a girlfrie...   

                                            clean_tweet  
0                                             follow (:  
1       great mann god follow   realise brow get bt ...  
2                                          snow cleaner  
3                                                   lol  
4                               lady nice rude behavior  
...                                                 ...  
5995  beforeidie wanna hav family like hood negro re...  
5996    m try tell d help cuz nick nt kno apologize ...  
5997                  lunch thank god mind leave hungry  
5998  ahahah read   dm ... lil brow   .. fool hit ge...  
5999                  girlfriend wud girlfriend ... lol  

[6000 rows x 8 columns]

In [73]:
yfeatures = ['Latitude','Longitude']
y = df[yfeatures]

In [74]:
bin_name = 'bin_'
for i in range(0,24*2):
    #print(i , end=',')
    df.loc[:,bin_name+str(i)] = 0

In [75]:
df

id   Latitude   Longitude  \
0     USER_131347  25.587695  -80.379636   
1     USER_321775  34.046692 -117.524254   
2     USER_139842  42.286785  -85.590620   
3     USER_362638  39.355249  -76.598514   
4     USER_311240  40.648491  -73.962830   
...           ...        ...         ...   
5995  USER_306230  40.685128  -73.581845   
5996  USER_247488  41.650608  -70.299491   
5997  USER_325702  39.070599  -77.011907   
5998  USER_235606  33.649463  -84.002263   
5999  USER_298845  35.995759  -78.888912   

                                                  tweet  tweet_count  \
0                          @USER_4beb918b followingg (:           24   
1     @USER_c586797f WHATZ GREAT MANN OF GOD, IF YOU...           33   
2     @USER_03159296 I'd have to go with the snow, i...           38   
3                                @USER_bcfa504a yup lol           20   
4                      Ladies be nice. No rude behavior           20   
...                                                 ...          ...   
5995  #beforeidie i wanna hav a family, somethin lik...           75   
5996  @USER_88b09e4d im not trying to ! i told her i...           23   
5997  RT @USER_8bde831b: Almost lunch thank God just...           41   
5998  aaahhh just read @USER_34876f43 dm...where my ...           43   
5999  If I had a girlfriend, she wud have a girlfrie...           25   

                                       tweet_timestamps  \
0     ['23:40:22', '11:39:18', '19:50:35', '21:29:39...   
1     ['22:50:47', '01:10:21', '03:13:05', '03:30:42...   
2     ['23:40:01', '23:42:45', '00:02:50', '00:09:07...   
3     ['16:51:44', '17:40:36', '17:48:26', '17:49:08...   
4     ['23:24:15', '23:56:40', '00:03:54', '02:53:08...   
...                                                 ...   
5995  ['22:58:19', '23:45:29', '00:16:39', '00:18:38...   
5996  ['14:39:16', '14:55:18', '15:03:54', '15:07:45...   
5997  ['22:45:21', '22:47:06', '22:49:13', '22:54:22...   
5998  ['22:43:27', '22:43:47', '22:50:12', '00:55:55...   
5999  ['02:42:09', '03:56:38', '13:24:48', '14:29:09...   

                                         tweet w/o user  \
0                                         followingg (:   
1      WHATZ GREAT MANN OF GOD, IF YOUR NOT FOLLOWIN...   
2      I'd have to go with the snow, it's much cleaner.   
3                                               yup lol   
4                      Ladies be nice. No rude behavior   
...                                                 ...   
5995  #beforeidie i wanna hav a family, somethin lik...   
5996   im not trying to ! i told her id help her its...   
5997  RT : Almost lunch thank God just 5mins left I'...   
5998  aaahhh just read  dm...where my lil bro  at..f...   
5999  If I had a girlfriend, she wud have a girlfrie...   

                                            clean_tweet  bin_0  bin_1  ...  \
0                                             follow (:      0      0  ...   
1       great mann god follow   realise brow get bt ...      0      0  ...   
2                                          snow cleaner      0      0  ...   
3                                                   lol      0      0  ...   
4                               lady nice rude behavior      0      0  ...   
...                                                 ...    ...    ...  ...   
5995  beforeidie wanna hav family like hood negro re...      0      0  ...   
5996    m try tell d help cuz nick nt kno apologize ...      0      0  ...   
5997                  lunch thank god mind leave hungry      0      0  ...   
5998  ahahah read   dm ... lil brow   .. fool hit ge...      0      0  ...   
5999                  girlfriend wud girlfriend ... lol      0      0  ...   

      bin_38  bin_39  bin_40  bin_41  bin_42  bin_43  bin_44  bin_45  bin_46  \
0          0       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          0       0      

In [76]:
s = df['tweet_timestamps'].str.split(',')
s
total_rows = df.shape[0]
for row in range(0,total_rows):
    #print(row,end=',')
    for time in s[row]:
        list_hour = time.split(':')[0]
        list_hour = re.findall('[0-9]+'  ,list_hour)
        hour_bin = int(list_hour[0])
        minute = int(time.split(':')[1])
        if(minute<29):
            minute_bin=0
        else:
            minute_bin = 1

        bin_number = 'bin_'+ str(hour_bin*2 + minute_bin)
        df.loc[row,bin_number] = df.loc[row,bin_number] + 1

In [77]:
df

id   Latitude   Longitude  \
0     USER_131347  25.587695  -80.379636   
1     USER_321775  34.046692 -117.524254   
2     USER_139842  42.286785  -85.590620   
3     USER_362638  39.355249  -76.598514   
4     USER_311240  40.648491  -73.962830   
...           ...        ...         ...   
5995  USER_306230  40.685128  -73.581845   
5996  USER_247488  41.650608  -70.299491   
5997  USER_325702  39.070599  -77.011907   
5998  USER_235606  33.649463  -84.002263   
5999  USER_298845  35.995759  -78.888912   

                                                  tweet  tweet_count  \
0                          @USER_4beb918b followingg (:           24   
1     @USER_c586797f WHATZ GREAT MANN OF GOD, IF YOU...           33   
2     @USER_03159296 I'd have to go with the snow, i...           38   
3                                @USER_bcfa504a yup lol           20   
4                      Ladies be nice. No rude behavior           20   
...                                                 ...          ...   
5995  #beforeidie i wanna hav a family, somethin lik...           75   
5996  @USER_88b09e4d im not trying to ! i told her i...           23   
5997  RT @USER_8bde831b: Almost lunch thank God just...           41   
5998  aaahhh just read @USER_34876f43 dm...where my ...           43   
5999  If I had a girlfriend, she wud have a girlfrie...           25   

                                       tweet_timestamps  \
0     ['23:40:22', '11:39:18', '19:50:35', '21:29:39...   
1     ['22:50:47', '01:10:21', '03:13:05', '03:30:42...   
2     ['23:40:01', '23:42:45', '00:02:50', '00:09:07...   
3     ['16:51:44', '17:40:36', '17:48:26', '17:49:08...   
4     ['23:24:15', '23:56:40', '00:03:54', '02:53:08...   
...                                                 ...   
5995  ['22:58:19', '23:45:29', '00:16:39', '00:18:38...   
5996  ['14:39:16', '14:55:18', '15:03:54', '15:07:45...   
5997  ['22:45:21', '22:47:06', '22:49:13', '22:54:22...   
5998  ['22:43:27', '22:43:47', '22:50:12', '00:55:55...   
5999  ['02:42:09', '03:56:38', '13:24:48', '14:29:09...   

                                         tweet w/o user  \
0                                         followingg (:   
1      WHATZ GREAT MANN OF GOD, IF YOUR NOT FOLLOWIN...   
2      I'd have to go with the snow, it's much cleaner.   
3                                               yup lol   
4                      Ladies be nice. No rude behavior   
...                                                 ...   
5995  #beforeidie i wanna hav a family, somethin lik...   
5996   im not trying to ! i told her id help her its...   
5997  RT : Almost lunch thank God just 5mins left I'...   
5998  aaahhh just read  dm...where my lil bro  at..f...   
5999  If I had a girlfriend, she wud have a girlfrie...   

                                            clean_tweet  bin_0  bin_1  ...  \
0                                             follow (:      2      1  ...   
1       great mann god follow   realise brow get bt ...      1      1  ...   
2                                          snow cleaner      3      0  ...   
3                                                   lol      0      0  ...   
4                               lady nice rude behavior      2      0  ...   
...                                                 ...    ...    ...  ...   
5995  beforeidie wanna hav family like hood negro re...      2      2  ...   
5996    m try tell d help cuz nick nt kno apologize ...      0      0  ...   
5997                  lunch thank god mind leave hungry      1      4  ...   
5998  ahahah read   dm ... lil brow   .. fool hit ge...      0      2  ...   
5999                  girlfriend wud girlfriend ... lol      0      0  ...   

      bin_38  bin_39  bin_40  bin_41  bin_42  bin_43  bin_44  bin_45  bin_46  \
0          0       4       0       1       1       2       1       0       1   
1          1       4       1       3       1       0       2       3       1   
2          3       0      

In [78]:
xfeatures = ['tweet_count', 'bin_0', 'bin_1', 'bin_2', 'bin_3',
       'bin_4', 'bin_5', 'bin_6', 'bin_7', 'bin_8', 'bin_9', 'bin_10',
       'bin_11', 'bin_12', 'bin_13', 'bin_14', 'bin_15', 'bin_16', 'bin_17',
       'bin_18', 'bin_19', 'bin_20', 'bin_21', 'bin_22', 'bin_23', 'bin_24',
       'bin_25', 'bin_26', 'bin_27', 'bin_28', 'bin_29', 'bin_30', 'bin_31',
       'bin_32', 'bin_33', 'bin_34', 'bin_35', 'bin_36', 'bin_37', 'bin_38',
       'bin_39', 'bin_40', 'bin_41', 'bin_42', 'bin_43', 'bin_44', 'bin_45',
       'bin_46', 'bin_47']
yfeatures = ['Latitude','Longitude']

In [79]:
X = df[xfeatures]
y = df[yfeatures]

In [80]:
X_np = X.values
X

Object `X_np = X.values` not found.


tweet_count  bin_0  bin_1  bin_2  bin_3  bin_4  bin_5  bin_6  bin_7  \
0              24      2      1      1      0      0      0      0      0   
1              33      1      1      1      0      0      0      1      1   
2              38      3      0      2      0      3      4      1      0   
3              20      0      0      0      0      1      0      0      0   
4              20      2      0      1      0      0      2      0      2   
...           ...    ...    ...    ...    ...    ...    ...    ...    ...   
5995           75      2      2      1      6      7      6      1      2   
5996           23      0      0      0      2      0      0      0      0   
5997           41      1      4      1      1      2      1      2      1   
5998           43      0      2      4      1      2      0      0      0   
5999           25      0      0      0      0      0      1      0      1   

      bin_8  ...  bin_38  bin_39  bin_40  bin_41  bin_42  bin_43  bin_44  \
0         0  ...       0       4       0       1       1       2       1   
1         0  ...       1       4       1       3       1       0       2   
2         2  ...       3       0       0       1       0       1       0   
3         0  ...       2       0       0       0       0       0       0   
4         1  ...       0       2       0       0       1       0       1   
...     ...  ...     ...     ...     ...     ...     ...     ...     ...   
5995      1  ...       1       0       1       1       1       0       0   
5996      0  ...       0       0       3       2       4       3       3   
5997      2  ...       0       1       0       3       1       0       0   
5998      0  ...       2       0       0       0       1       0       0   
5999      2  ...       0       0       0       1       0       0       0   

      bin_45  bin_46  bin_47  
0          0       1       2  
1          3       1       1  
2          1       0       3  
3          0       0       0  
4          0       1       1  
...      ...     ...     ...  
5995       1       0       6  
5996       0       0       0  
5997       5       0       2  
5998       3       0       0  
5999       0       0       0  

[6000 rows x 49 columns]

In [81]:
final_X_np = np.concatenate((X_np, flattened_embedded_matrix), axis=1)
final_X_np

array([[ 2.40000000e+01,  2.00000000e+00,  1.00000000e+00, ...,
        -2.40256432e-02,  4.66271304e-02,  1.84296444e-03],
       [ 3.30000000e+01,  1.00000000e+00,  1.00000000e+00, ...,
        -3.17035690e-02,  3.73451747e-02, -3.71480584e-02],
       [ 3.80000000e+01,  3.00000000e+00,  0.00000000e+00, ...,
        -1.92257892e-02,  3.75586785e-02, -3.60031016e-02],
       ...,
       [ 4.10000000e+01,  1.00000000e+00,  4.00000000e+00, ...,
         2.79309489e-02,  4.04331721e-02, -9.27956030e-03],
       [ 4.30000000e+01,  0.00000000e+00,  2.00000000e+00, ...,
         3.97978313e-02,  4.46033739e-02, -1.67690516e-02],
       [ 2.50000000e+01,  0.00000000e+00,  0.00000000e+00, ...,
         4.91379835e-02,  2.86184251e-04,  6.00381941e-03]])

In [82]:
final_X_np[0][:50]

array([24.        ,  2.        ,  1.        ,  1.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  2.        ,
        0.        ,  0.        ,  1.        ,  1.        ,  0.        ,
        0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
        0.        ,  1.        ,  1.        ,  0.        ,  0.        ,
        4.        ,  0.        ,  1.        ,  1.        ,  2.        ,
        1.        ,  0.        ,  1.        ,  2.        ,  0.04798564])

In [83]:
y_np = y.values

In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(final_X_np, y_np, test_size=0.2, random_state=42)

In [85]:
scale_columns = X_train[:,:49]
print(scale_columns[0])

[44.  2.  3.  0.  8. 10.  5.  1.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  2.  0.  0.  0.  0.  0.
  0.  1.  3.  0.  0.  0.  0.  1.  0.  2.  0.  2.  0.]


In [86]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scale_columns_after = scaler.fit_transform(scale_columns)
scale_columns_after[0]

array([0.08540925, 0.125     , 0.21428571, 0.        , 0.66666667,
       0.71428571, 0.23809524, 0.05555556, 0.        , 0.05882353,
       0.        , 0.        , 0.        , 0.        , 0.05555556,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07692308, 0.07692308,
       0.15384615, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07692308, 0.15      , 0.        ,
       0.        , 0.        , 0.        , 0.07142857, 0.        ,
       0.13333333, 0.        , 0.125     , 0.        ])

In [87]:
X_train[:, :49] = scale_columns_after

In [88]:
scale_columns_test = X_test[:,:49]
scale_columns_after_test = scaler.transform(scale_columns_test)
scale_columns_after_test[0]

array([0.0747331 , 0.0625    , 0.07142857, 0.        , 0.        ,
       0.14285714, 0.04761905, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.0952381 , 0.05555556,
       0.        , 0.        , 0.07142857, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.46153846, 0.25      , 0.16666667,
       0.        , 0.45454545, 0.2       , 0.07142857, 0.14285714,
       0.06666667, 0.        , 0.25      , 0.08333333])

In [89]:
X_test[:, :49] = scale_columns_after_test

In [90]:
X_train.shape[1]

449

In [40]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Define your ANN model
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(2)  # Output layer with 2 neurons for latitude and longitude prediction
])

# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Print the model summary
model.summary()

# Fit the model to the training data
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

mse, mae = model.evaluate(X_test, y_test)
print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               57600     
                                                                 
 dense_1 (Dense)             (None, 128)               16512     
                                                                 
 dense_2 (Dense)             (None, 64)                8256      
                                                                 
 dense_3 (Dense)             (None, 32)                2080      
                                                                 
 dense_4 (Dense)             (None, 16)                528       
                                                                 
 dense_5 (Dense)             (None, 2)                 34        
                                                                 
Total params: 85010 (332.07 KB)
Trainable params: 8501

In [ ]:
#128,64,32,16 ---> 138mse

In [ ]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error

# Define the XGBoost model
xgb_model = xgb.XGBRegressor(objective ='reg:squarederror',
                             colsample_bytree = 0.3,
                             learning_rate = 0.1,
                             max_depth = 3,
                             alpha = 10,
                             n_estimators = 100)  # You can adjust hyperparameters as needed

# Train the model
xgb_model.fit(X_train, y_train)

# Make predictions on the test data
y_pred_xgb = xgb_model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred_xgb)
print("Mean Squared Error:", mse)

Mean Squared Error: 136.84967058037873


In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Define your RNN model
model = Sequential([
    LSTM(128, activation='relu', input_shape=(X_train.shape[1], X_train.shape[2])),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(2)  # Output layer with 2 neurons for latitude and longitude prediction
])

# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Print the model summary
model.summary()

# Fit the model to the training data
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

mse, mae = model.evaluate(X_test, y_test)
print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)


IndexError: tuple index out of range

In [93]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Reshape X_train for sequence modeling
X_train_reshaped = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))
X_test_reshaped = X_test.reshape((X_test.shape[0], 1, X_test.shape[1]))

# Define your RNN model
model = Sequential([
    LSTM(128, activation='relu', input_shape=(X_train_reshaped.shape[1], X_train_reshaped.shape[2])),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(2)  # Output layer with 2 neurons for latitude and longitude prediction
])

# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Print the model summary
model.summary()

# Fit the model to the training data
history = model.fit(X_train_reshaped, y_train, epochs=10, batch_size=32, validation_split=0.1)

# Assuming X_test and y_test have similar preprocessing as X_train and y_train
mse, mae = model.evaluate(X_test_reshaped, y_test)
print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)


Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_6 (LSTM)               (None, 128)               295936    
                                                                 
 dense_25 (Dense)            (None, 128)               16512     
                                                                 
 dense_26 (Dense)            (None, 64)                8256      
                                                                 
 dense_27 (Dense)            (None, 32)                2080      
                                                                 
 dense_28 (Dense)            (None, 16)                528       
                                                                 
 dense_29 (Dense)            (None, 2)                 34        
                                                                 
Total params: 323346 (1.23 MB)
Trainable params: 32334

In [94]:
twitter_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Bayesian Learning/Project 1/Trial 6/test.csv', encoding = 'ISO-8859-1')
df_test = twitter_data.iloc[:2000]
df_test

id                                              tweet  \
0     USER_260308  RT @USER_ae4fbb59: its very rare but sometimes...   
1     USER_139695  Uhhhh I'm not goin to thee game I wanted to bu...   
2     USER_176526                          @USER_1c9b55c9 follow me!   
3     USER_151041                            @USER_18cf664a yay!! Ok   
4     USER_267845                              42nd with the girls .   
...           ...                                                ...   
1995  USER_158534                            Man WTF is DUKE doin!!!   
1996  USER_339095  I really be wondering what do people do here l...   
1997  USER_329120                                    I need a nap :[   
1998  USER_248527  I don't give a fuck who do like me in linden p...   
1999  USER_118682  @USER_34469ebb thanx man, but my bday was Tues...   

      tweet_count                                   tweet_timestamps  
0              24  ['22:48:01', '23:57:58', '17:47:26', '18:24:33...  
1              35  ['15:35:20', '16:03:17', '18:08:54', '20:48:33...  
2              22  ['16:32:37', '21:37:26', '12:37:10', '13:02:16...  
3              34  ['02:14:35', '21:15:55', '05:25:31', '16:25:50...  
4              24  ['03:08:38', '03:33:40', '03:37:46', '03:49:56...  
...           ...                                                ...  
1995           32  ['03:05:26', '03:07:42', '03:25:22', '03:30:19...  
1996           41  ['04:28:41', '05:25:41', '17:14:45', '17:33:21...  
1997           43  ['22:53:57', '23:23:16', '23:32:08', '23:59:58...  
1998           71  ['23:31:33', '00:44:58', '00:49:54', '03:49:46...  
1999           32  ['02:12:08', '02:13:37', '00:08:22', '00:34:12...  

[2000 rows x 4 columns]

In [95]:
def remove_user_tweet(tweet):
    pattern = '[@][a-zA-Z0-9_]*'
    #matches = re.findall(pattern  ,tweet)
    match = re.compile( '[@][a-zA-Z0-9_]*')
    sentence = match.sub('', tweet)
    return sentence

In [96]:
df_test.loc[:,'tweet w/o user'] = df_test.loc[:,'tweet'].apply(remove_user_tweet)
df_test

<ipython-input-96-1c790572f70e>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test.loc[:,'tweet w/o user'] = df_test.loc[:,'tweet'].apply(remove_user_tweet)


id                                              tweet  \
0     USER_260308  RT @USER_ae4fbb59: its very rare but sometimes...   
1     USER_139695  Uhhhh I'm not goin to thee game I wanted to bu...   
2     USER_176526                          @USER_1c9b55c9 follow me!   
3     USER_151041                            @USER_18cf664a yay!! Ok   
4     USER_267845                              42nd with the girls .   
...           ...                                                ...   
1995  USER_158534                            Man WTF is DUKE doin!!!   
1996  USER_339095  I really be wondering what do people do here l...   
1997  USER_329120                                    I need a nap :[   
1998  USER_248527  I don't give a fuck who do like me in linden p...   
1999  USER_118682  @USER_34469ebb thanx man, but my bday was Tues...   

      tweet_count                                   tweet_timestamps  \
0              24  ['22:48:01', '23:57:58', '17:47:26', '18:24:33...   
1              35  ['15:35:20', '16:03:17', '18:08:54', '20:48:33...   
2              22  ['16:32:37', '21:37:26', '12:37:10', '13:02:16...   
3              34  ['02:14:35', '21:15:55', '05:25:31', '16:25:50...   
4              24  ['03:08:38', '03:33:40', '03:37:46', '03:49:56...   
...           ...                                                ...   
1995           32  ['03:05:26', '03:07:42', '03:25:22', '03:30:19...   
1996           41  ['04:28:41', '05:25:41', '17:14:45', '17:33:21...   
1997           43  ['22:53:57', '23:23:16', '23:32:08', '23:59:58...   
1998           71  ['23:31:33', '00:44:58', '00:49:54', '03:49:46...   
1999           32  ['02:12:08', '02:13:37', '00:08:22', '00:34:12...   

                                         tweet w/o user  
0        RT : its very rare but sometimes I can be mean  
1     Uhhhh I'm not goin to thee game I wanted to bu...  
2                                            follow me!  
3                                              yay!! Ok  
4                                 42nd with the girls .  
...                                                 ...  
1995                            Man WTF is DUKE doin!!!  
1996  I really be wondering what do people do here l...  
1997                                    I need a nap :[  
1998  I don't give a fuck who do like me in linden p...  
1999   thanx man, but my bday was Tuesday. I'm just ...  

[2000 rows x 5 columns]

In [48]:
import pandas as pd
import re
import nltk
import spacy
import numpy as np
from textblob import TextBlob
import gensim
nlp = spacy.load('en_core_web_sm')

In [97]:
def process_words(tweet):
    tweet = tweet.lower()
    shortform = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Bayesian Learning/Project 1/Trial 6/abbreviations.csv')
    shortform_list = shortform['abbreviation'].tolist()
    doc = nlp(tweet)

    # p = []
    # for i in string.punctuation:
    # p.append(i)

    punctuations = [',','!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', ':', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~']

    tweet_corrected = []
    #correct spelling in the tweets.

    #dont touch shortforms
    for word in doc:
        if str(word) not in shortform_list:
            tweet_corrected_word = nlp(str(TextBlob(str(word)).correct()))[0]

            #doc2 = nlp(tweet_corrected_word)
            if not (tweet_corrected_word).is_stop:
                #print("not stop", tweet_corrected_word)
                if((str(tweet_corrected_word)) not in punctuations):
                     #print("punctionation not found:",tweet_corrected_word)


                     tweet_corrected.append(tweet_corrected_word.lemma_)


        else:
            tweet_corrected.append(str(word))
            #print("found " ,word)

    sentence = ' '.join(tweet_corrected)
    return sentence

In [98]:
df_test.loc[:,'clean_tweet'] = df_test.loc[:,'tweet w/o user'].progress_apply(process_words)

100%|██████████| 2000/2000 [12:06<00:00,  2.75it/s]
<ipython-input-98-c24ed0381c26>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test.loc[:,'clean_tweet'] = df_test.loc[:,'tweet w/o user'].progress_apply(process_words)


In [99]:
tweets = df_test['clean_tweet']
tweets

0                                               rare mean
1       uhhhh goin thee game want y support middle big...
2                                                  follow
3                                                      ok
4                                                    girl
                              ...                        
1995                                    man wtf duke doin
1996    wonder people like have aaalll time barely hav...
1997                                             need nap
1998    fuck like linen project 185 b exact ... ur n p...
1999             thanx man bday tuesday havin party today
Name: clean_tweet, Length: 2000, dtype: object

In [100]:
tweets = list(tweets)
tweets

['rare mean',
 'uhhhh goin thee game want y support middle big day   thee heat arena',
 '  follow',
 '  ok',
 'girl',
 '  yell dog scream speak admit proceed verbal debate universe',
 '  ... interesting long kill',
 'lol chicago til d   u go superstar',
 'trapper need simply fan mic ear bleed stop torture get station =(',
 'soon bore',
 '  oh right right',
 'marry',
 '  get fuckin trout like wtf',
 'hope get 63 wknd like forecast ...',
 'random get order 4 size 12 pair sparkle loubouton   work 2day automatically think goin 2 windy williams lol',
 '  watchin rate kid n gettin ready move wat u deal wit today',
 'hate ppl feel time b ugly smh damn shame',
 'letsbereal people r cheap fuck think everybody owe',
 '  lol',
 'bout ti green',
 'omg heaven find good vantage webster .. super excite',
 'oak class time',
 'highschool   bother chinese say cheese',
 '  wish bring blanket class it;--- lol thinkin thing',
 'o rich babe drive bury need helmet',
 'itsnotok like north carolina duke lol u 

In [101]:
sent = tweets[:]
sent

['rare mean',
 'uhhhh goin thee game want y support middle big day   thee heat arena',
 '  follow',
 '  ok',
 'girl',
 '  yell dog scream speak admit proceed verbal debate universe',
 '  ... interesting long kill',
 'lol chicago til d   u go superstar',
 'trapper need simply fan mic ear bleed stop torture get station =(',
 'soon bore',
 '  oh right right',
 'marry',
 '  get fuckin trout like wtf',
 'hope get 63 wknd like forecast ...',
 'random get order 4 size 12 pair sparkle loubouton   work 2day automatically think goin 2 windy williams lol',
 '  watchin rate kid n gettin ready move wat u deal wit today',
 'hate ppl feel time b ugly smh damn shame',
 'letsbereal people r cheap fuck think everybody owe',
 '  lol',
 'bout ti green',
 'omg heaven find good vantage webster .. super excite',
 'oak class time',
 'highschool   bother chinese say cheese',
 '  wish bring blanket class it;--- lol thinkin thing',
 'o rich babe drive bury need helmet',
 'itsnotok like north carolina duke lol u 

In [102]:
onehot_repr = [one_hot(str(words) , voc_size) for words in sent]
print(onehot_repr)

[[10336, 16189], [12681, 17681, 13777, 6630, 3690, 10267, 663, 19654, 14560, 4465, 13777, 7773, 10568], [8950], [9345], [295], [3480, 10991, 19841, 14256, 1091, 8802, 5143, 4008, 9019], [6991, 607, 3415], [10884, 10602, 10029, 13556, 16069, 8420, 19400], [7074, 9579, 10876, 2839, 17342, 11658, 15204, 18315, 17555, 9612, 482], [11230, 16510], [18640, 975, 975], [2319], [9612, 16031, 6934, 17518, 17922], [6065, 9612, 11847, 3677, 17518, 8088], [14933, 9612, 6759, 7336, 19643, 10301, 19852, 1309, 3572, 15638, 15158, 11646, 7725, 17681, 7664, 8931, 2799, 10884], [7057, 14556, 9859, 14180, 5192, 7837, 790, 1834, 16069, 2600, 13220, 19229], [17263, 9366, 19223, 10246, 10439, 419, 262, 19148, 5943], [11730, 161, 13575, 9565, 13140, 7725, 10896, 14203], [10884], [6087, 14868, 16854], [16135, 16814, 15544, 1871, 14381, 184, 10702, 15759], [16418, 2555, 10246], [17014, 13678, 16108, 14213, 2252], [19428, 1958, 15546, 2555, 1482, 10884, 2169, 4615], [18709, 1076, 13381, 7350, 1329, 9579, 10243], 

In [103]:
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen = sent_length)
print(embedded_docs)

[[    0     0     0 ...     0 10336 16189]
 [    0     0     0 ... 13777  7773 10568]
 [    0     0     0 ...     0     0  8950]
 ...
 [    0     0     0 ...     0  9579  1583]
 [    0     0     0 ...  3415   124 14317]
 [    0     0     0 ...  1051  9216 19229]]


In [104]:
embedded_matrix = model_emb.predict(embedded_docs)

63/63 [==============================] - 0s 1ms/step


In [105]:
flattened_embedded_matrix = embedded_matrix.reshape(embedded_matrix.shape[0], -1)
flattened_embedded_matrix

array([[ 4.7985639e-02, -3.6013544e-02,  2.1134567e-02, ...,
        -1.4232408e-02, -2.5498495e-03, -4.8447240e-02],
       [ 4.7985639e-02, -3.6013544e-02,  2.1134567e-02, ...,
         2.2095803e-02, -4.6453264e-02,  1.4825646e-02],
       [ 4.7985639e-02, -3.6013544e-02,  2.1134567e-02, ...,
        -2.4025643e-02,  4.6627130e-02,  1.8429644e-03],
       ...,
       [ 4.7985639e-02, -3.6013544e-02,  2.1134567e-02, ...,
         1.1506092e-02, -4.6546686e-02,  1.7978251e-05],
       [ 4.7985639e-02, -3.6013544e-02,  2.1134567e-02, ...,
         2.6421379e-02, -5.8187246e-03,  1.9742776e-02],
       [ 4.7985639e-02, -3.6013544e-02,  2.1134567e-02, ...,
         2.2128973e-02,  9.1240406e-03, -3.4987140e-02]], dtype=float32)

In [106]:
bin_name = 'bin_'
for i in range(0,24*2):
    #print(i , end=',')
    df_test.loc[:,bin_name+str(i)] = 0

<ipython-input-106-7b6a8b76fa86>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test.loc[:,bin_name+str(i)] = 0
<ipython-input-106-7b6a8b76fa86>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test.loc[:,bin_name+str(i)] = 0
<ipython-input-106-7b6a8b76fa86>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide

In [107]:
s = df_test['tweet_timestamps'].str.split(',')
s
total_rows = df_test.shape[0]
for row in range(0,total_rows):
    #print(row,end=',')
    for time in s[row]:
        list_hour = time.split(':')[0]
        list_hour = re.findall('[0-9]+'  ,list_hour)
        hour_bin = int(list_hour[0])
        minute = int(time.split(':')[1])
        if(minute<29):
            minute_bin=0
        else:
            minute_bin = 1

        bin_number = 'bin_'+ str(hour_bin*2 + minute_bin)
        df_test.loc[row,bin_number] = df_test.loc[row,bin_number] + 1

In [108]:
xfeatures = ['tweet_count', 'bin_0', 'bin_1', 'bin_2', 'bin_3',
       'bin_4', 'bin_5', 'bin_6', 'bin_7', 'bin_8', 'bin_9', 'bin_10',
       'bin_11', 'bin_12', 'bin_13', 'bin_14', 'bin_15', 'bin_16', 'bin_17',
       'bin_18', 'bin_19', 'bin_20', 'bin_21', 'bin_22', 'bin_23', 'bin_24',
       'bin_25', 'bin_26', 'bin_27', 'bin_28', 'bin_29', 'bin_30', 'bin_31',
       'bin_32', 'bin_33', 'bin_34', 'bin_35', 'bin_36', 'bin_37', 'bin_38',
       'bin_39', 'bin_40', 'bin_41', 'bin_42', 'bin_43', 'bin_44', 'bin_45',
       'bin_46', 'bin_47']
yfeatures = ['Latitude','Longitude']

In [110]:
X = df_test[xfeatures]

In [111]:
X_np = X.values
final_X_np = np.concatenate((X_np, flattened_embedded_matrix), axis=1)

In [ ]:
y_np = y.values

In [112]:
scale_columns = final_X_np[:,:49]
print(scale_columns[0])

[24.  0.  2.  2.  0.  0.  0.  0.  2.  0.  1.  1.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  2.
  1.  2.  2.  0.  0.  1.  0.  1.  2.  2.  1.  1.  1.]


In [113]:
scale_columns_after = scaler.transform(scale_columns)
scale_columns_after[0]

array([0.01423488, 0.        , 0.14285714, 0.14285714, 0.        ,
       0.        , 0.        , 0.        , 0.11764706, 0.        ,
       0.05882353, 0.06666667, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.15384615, 0.08333333, 0.15384615, 0.1       , 0.        ,
       0.        , 0.09090909, 0.        , 0.07142857, 0.14285714,
       0.13333333, 0.07692308, 0.0625    , 0.04166667])

In [114]:
final_X_np[:, :49] = scale_columns_after

In [116]:
final_X_np.shape

(2000, 449)

In [117]:
final_test_reshaped = final_X_np.reshape((final_X_np[0], 1, final_X_np.shape[1]))
y_pred = model.predict(final_test_reshaped)
y_pred

TypeError: only integer scalar arrays can be converted to a scalar index